---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

stages:
  - commit
  - syntax
  - test-centos
  - test-debian
  - test-devuan
  - test-ubuntu
  - module

# commit
git-history:
  stage: commit
  script:
    - >
      bash <(curl -s
      https://gitlab.com/yue-script/checks/raw/master/check_git_history.sh)

lines-length:
  stage: commit
  script:
    - >
      bash <(curl -s
      https://gitlab.com/yue-script/checks/raw/master/check_lines_length.sh)
      80 templates/* files/*

# syntax
erb-lint:
  stage: syntax
  image: vpgrp/linter:puppet
  script:
    - rails-erb-lint check --path=templates

json-lint:
  stage: syntax
  image: vpgrp/linter:json
  script:
    - metadata-json-lint metadata.json

puppet-lint:
  stage: syntax
  image: vpgrp/linter:puppet
  script:
    - puppet-lint --fail-on-warnings .

rubocop:
  stage: syntax
  image: vpgrp/linter:ruby
  script:
    - rubocop .

yaml-lint:
  stage: syntax
  image: vpgrp/linter:yaml
  script:
    - yaml-lint .gitlab-ci.yml
    - yaml-lint .kitchen.yml
    - yaml-lint .puppetforge.yml

# puppet
centos-6:
  stage: test-centos
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color centos-centos-6

centos-7:
  stage: test-centos
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color centos-centos-7

# Ruby 1.9 issue with Debian 5
# debian-5:
#   stage: test-debian
#   image: vpgrp/kitchen
#   script:
#     - kitchen test --destroy=always --color debian-debian-5
#     - kitchen test --destroy=always --color debian-debian-5-bpo
#   allow_failure: true

debian-6:
  stage: test-debian
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color debian-debian-6
    - kitchen test --destroy=always --color debian-debian-6-bpo
  allow_failure: true

debian-7:
  stage: test-debian
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color debian-debian-7
    - kitchen test --destroy=always --color debian-debian-7-bpo

debian-8:
  stage: test-debian
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color debian-debian-8
    - kitchen test --destroy=always --color debian-debian-8-bpo

debian-9:
  stage: test-debian
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color debian-debian-9
    - kitchen test --destroy=always --color debian-debian-9-bpo

debian-10:
  stage: test-debian
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color debian-debian-10
    - kitchen test --destroy=always --color debian-debian-10-bpo

# Serverspec issue with Devuan 1
# devuan-1:
#   stage: test-devuan
#   image: vpgrp/kitchen
#   script:
#     - kitchen test --destroy=always --color devuan-devuan-1
#   allow_failure: true

# Ruby 1.9 issue with Ubuntu 10.04
# ubuntu-10.04:
#   stage: test-ubuntu
#   image: vpgrp/kitchen
#   script:
#     - kitchen test --destroy=always --color ubuntu-ubuntu-10-04
#   allow_failure: true

ubuntu-12.04:
  stage: test-ubuntu
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color ubuntu-ubuntu-12-04

ubuntu-14.04:
  stage: test-ubuntu
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color ubuntu-ubuntu-14-04

ubuntu-16.04:
  stage: test-ubuntu
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color ubuntu-ubuntu-16-04

# create module
create-module:
  stage: module
  image: vpgrp/puppet
  script:
    - puppet module build

publish-module:
  stage: module
  only:
    - master
  image: vpgrp/puppet
  script:
    - rake module:push
# EOF
